name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-linters:
    name: Run linters
    runs-on: windows-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run linters
        run: dotnet format '.\LIS\LIS.csproj' --check --verbosity diagnostic
          
  docker:
    timeout-minutes: 10
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Run tests
      run: docker-compose run test

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
